# Generated by Django 4.0.6 on 2022-07-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_review_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
